# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('real_name', models.CharField(max_length=500)),
                ('tz', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.User'),
        ),
    ]
