# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
