# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20200812_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.CharField(max_length=500),
        ),
    ]
